In [1]:
!pip install natsort
from vollseg import inrimage
import napari
import os
import numpy as np
import glob
from pathlib import Path
from natsort import natsorted
from tifffile import imread, imwrite
%gui qt

DIPlib -- a quantitative image analysis library
Version 3.1.0 (Sep 24 2021)
For more information see https://diplib.org


In [2]:
sourcedir = '/mnt/d/LightSheetRaw/Astec-half-Pm1/POST/POST_RELEASE/'
savedir = '/mnt/d/LightSheetRaw/Astec-half-Pm1/POST/POST_RELEASE/Tif_files/'
Path(savedir).mkdir(exist_ok=True)
Raw_path = os.path.join(sourcedir, '*.gz')
filesRaw = glob.glob(Raw_path)
filesRaw = natsorted(filesRaw)
for fname in filesRaw:
    image = inrimage.read_inrimage(fname)
   
    Name = os.path.basename(os.path.splitext(fname)[0]) 
    imwrite(savedir + '/' + Name + '.tif', image.astype('float16') )


In [14]:
print(image.shape)

(10, 10)


In [4]:
viewer = napari.Viewer()
viewer.dims.ndisplay = 3
viewer.add_image(image)

<Image layer 'image' at 0x7f3c3eed2b20>

In [20]:
import numpy as np
from tqdm import tqdm
image = np.random.rand(10,10,10)
for _x in tqdm(image):
    print(_x.shape)

100%|████████████████████████████████████████████████████████████████████████████████| 10/10 [00:00<00:00, 21597.86it/s]

(10, 10)
(10, 10)
(10, 10)
(10, 10)
(10, 10)
(10, 10)
(10, 10)
(10, 10)
(10, 10)
(10, 10)


In [8]:
%gui qt

In [13]:
import napari
viewer = napari.Viewer()
image = np.random.rand(10,10)*100

viewer.add_labels(image.astype('uint16'), name = 'label')
data = viewer.layers['label'].data
print(data)

[[ 2 84 84 46 34 84 55 76 86 64]
 [20 15 69 49 91 78 17 52  5 60]
 [45 18 19 31 63 20 93 94 97 21]
 [39 41 26 75 64  2 66 22 19 67]
 [26 94 86 41 50 16 99 17 93 71]
 [83 47 25 99 57 28 47 57 41 37]
 [71 17 87  2  3 11 11 92 61 26]
 [ 8 64 51 37 80 23 83 60  1 36]
 [64  3 74 75 57 28 13 40  2 84]
 [39 30 17  5 76 71 73 66 63 92]]
